apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  rules:
  - host: grafana.test-cluster.k9s.a9s-ops.de
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
