apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
  labels:
    app: logger
spec:
  replicas: 50
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: chentex/random-logger
