
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/vcap/data/grafana
            name: grafana-persistent-storage-store
          - mountPath: /etc/grafana/provisioning/datasources/datasource.yml
            name: grafana-datasources
            subPath: datasource.yaml
            readOnly: false
      volumes:
        - name: grafana-persistent-storage-store
          persistentVolumeClaim:
            claimName: grafana-storage-pvc
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
