apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
    loki.yaml: |-
      {
          "apiVersion": 1,
          "datasources": [
              {
                 "access":"proxy",
                  "editable": true,
                  "name": "loki",
                  "orgId": 1,
                  "type": "loki",
                  "url": "http://loki.monitoring.svc.cluster.local:3100",
                  "version": 1
              }
          ]
      }
