apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
    datasource.yaml: |
      apiVersion: 1
      datasources:
        - name: loki
          type: loki
          access: proxy
          version: 1
          editable: true
          orgId: 1
          url: http://loki.monitoring.svc.cluster.local:3100
